// Autogenerated from KST: please remove this line if doing any edits by hand!

use std::fs;
extern crate kaitai;
use self::kaitai::*;
use rust::formats::oper_precedence_sum2::*;

#[test]
fn test_oper_precedence_sum2() -> KResult<()> {
    let bytes = fs::read("../../src/fixed_struct.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let r: OptRc<OperPrecedenceSum2> = OperPrecedenceSum2::read_into(&_io, None, None)?;

    assert_eq!(*r.sum()?, 6);
    assert_eq!(*r.sub()?, 0);
    assert_eq!(*r.mul()?, 9);
    assert_eq!(*r.div_int()?, 1);
    assert_eq!(*r.div_float1()?, 1.0);
    assert_eq!(*r.div_float2()?, 1.0);
    assert_eq!(*r.rem()?, 0);
    assert_eq!(*r.shl()?, 24);
    assert_eq!(*r.shr()?, 0);
    assert_eq!(*r.bit_and()?, 3);
    assert_eq!(*r.bit_or()?, 3);
    assert_eq!(*r.bit_xor()?, 0);
    assert_eq!(*r.eq()?, true);
    assert_eq!(*r.ne()?, false);
    assert_eq!(*r.le()?, true);
    assert_eq!(*r.ge()?, true);
    assert_eq!(*r.lt()?, false);
    assert_eq!(*r.gt()?, false);
    Ok(())
}
