// Autogenerated from KST: please remove this line if doing any edits by hand!

use std::fs;
extern crate kaitai;
use self::kaitai::*;
use rust::formats::oper_precedence_sum3::*;

#[test]
fn test_oper_precedence_sum3() -> KResult<()> {
    let bytes = fs::read("../../src/fixed_struct.bin").unwrap();
    let _io = BytesReader::from(bytes);
    let r: OptRc<OperPrecedenceSum3> = OperPrecedenceSum3::read_into(&_io, None, None)?;

    assert_eq!(*r.sum()?, 6);
    assert_eq!(*r.sub()?, 0);
    assert_eq!(*r.mul()?, 7);
    assert_eq!(*r.div_int()?, 2);
    assert_eq!(*r.div_float1()?, 1.6666666);
    assert_eq!(*r.div_float2()?, 1.6666666);
    assert_eq!(*r.rem()?, 3);
    assert_eq!(*r.shl()?, 17);
    assert_eq!(*r.shr()?, 1);
    assert_eq!(*r.bit_and()?, 3);
    assert_eq!(*r.bit_or()?, 4);
    assert_eq!(*r.bit_xor()?, 2);
    Ok(())
}
