# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest
from testformats.oper_precedence_sum2 import OperPrecedenceSum2

class TestOperPrecedenceSum2(unittest.TestCase):
    def test_oper_precedence_sum2(self):
        with OperPrecedenceSum2.from_file('src/fixed_struct.bin') as r:
            self.assertEqual(r.sum, 6)
            self.assertEqual(r.sub, 0)
            self.assertEqual(r.mul, 9)
            self.assertEqual(r.div_int, 1)
            self.assertAlmostEqual(r.div_float1, 1.0, 6)
            self.assertAlmostEqual(r.div_float2, 1.0, 6)
            self.assertEqual(r.rem, 0)
            self.assertEqual(r.shl, 24)
            self.assertEqual(r.shr, 0)
            self.assertEqual(r.bit_and, 3)
            self.assertEqual(r.bit_or, 3)
            self.assertEqual(r.bit_xor, 0)
            self.assertEqual(r.eq, True)
            self.assertEqual(r.ne, False)
            self.assertEqual(r.le, True)
            self.assertEqual(r.ge, True)
            self.assertEqual(r.lt, False)
            self.assertEqual(r.gt, False)
