// Autogenerated from KST: please remove this line if doing any edits by hand!

var assert = require('assert');
var testHelper = require('testHelper');

testHelper('OperPrecedenceSum3', 'src/fixed_struct.bin', function(r, OperPrecedenceSum3_) {
  assert.strictEqual(r.sum, 6);
  assert.strictEqual(r.sub, 0);
  assert.strictEqual(r.mul, 7);
  assert.strictEqual(r.divInt, 2);
  assert(Math.abs(r.divFloat1 - 1.6666666) < 1e-6);
  assert(Math.abs(r.divFloat2 - 1.6666666) < 1e-6);
  assert.strictEqual(r.rem, 3);
  assert.strictEqual(r.shl, 17);
  assert.strictEqual(r.shr, 1);
  assert.strictEqual(r.bitAnd, 3);
  assert.strictEqual(r.bitOr, 4);
  assert.strictEqual(r.bitXor, 2);
});
