# Autogenerated from KST: please remove this line if doing any edits by hand!

RSpec.describe 'OperPrecedenceSum3' do
  it 'parses test properly' do
    require 'oper_precedence_sum3'
    r = OperPrecedenceSum3.from_file('src/fixed_struct.bin')

    expect(r.sum).to eq 6
    expect(r.sub).to eq 0
    expect(r.mul).to eq 7
    expect(r.div_int).to eq 2
    expect(r.div_float1).to be_within(1e-6).of 1.6666666
    expect(r.div_float2).to be_within(1e-6).of 1.6666666
    expect(r.rem).to eq 3
    expect(r.shl).to eq 17
    expect(r.shr).to eq 1
    expect(r.bit_and).to eq 3
    expect(r.bit_or).to eq 4
    expect(r.bit_xor).to eq 2
  end
end
