// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec;

import io.kaitai.struct.testformats.OperPrecedenceSum2;
import org.testng.annotations.Test;
import static org.testng.Assert.*;
public class TestOperPrecedenceSum2 extends CommonSpec {
    @Test
    public void testOperPrecedenceSum2() throws Exception {
        OperPrecedenceSum2 r = OperPrecedenceSum2.fromFile(SRC_DIR + "fixed_struct.bin");

        assertIntEquals(r.sum(), 6);
        assertIntEquals(r.sub(), 0);
        assertIntEquals(r.mul(), 9);
        assertIntEquals(r.divInt(), 1);
        assertEquals(r.divFloat1(), 1.0, 1e-6);
        assertEquals(r.divFloat2(), 1.0, 1e-6);
        assertIntEquals(r.rem(), 0);
        assertIntEquals(r.shl(), 24);
        assertIntEquals(r.shr(), 0);
        assertIntEquals(r.bitAnd(), 3);
        assertIntEquals(r.bitOr(), 3);
        assertIntEquals(r.bitXor(), 0);
        assertIntEquals(r.eq(), true);
        assertIntEquals(r.ne(), false);
        assertIntEquals(r.le(), true);
        assertIntEquals(r.ge(), true);
        assertIntEquals(r.lt(), false);
        assertIntEquals(r.gt(), false);
    }
}
