// Autogenerated from KST: please remove this line if doing any edits by hand!

package io.kaitai.struct.spec;

import io.kaitai.struct.testformats.OperPrecedenceSum3;
import org.testng.annotations.Test;
import static org.testng.Assert.*;
public class TestOperPrecedenceSum3 extends CommonSpec {
    @Test
    public void testOperPrecedenceSum3() throws Exception {
        OperPrecedenceSum3 r = OperPrecedenceSum3.fromFile(SRC_DIR + "fixed_struct.bin");

        assertIntEquals(r.sum(), 6);
        assertIntEquals(r.sub(), 0);
        assertIntEquals(r.mul(), 7);
        assertIntEquals(r.divInt(), 2);
        assertEquals(r.divFloat1(), 1.6666666, 1e-6);
        assertEquals(r.divFloat2(), 1.6666666, 1e-6);
        assertIntEquals(r.rem(), 3);
        assertIntEquals(r.shl(), 17);
        assertIntEquals(r.shr(), 1);
        assertIntEquals(r.bitAnd(), 3);
        assertIntEquals(r.bitOr(), 4);
        assertIntEquals(r.bitXor(), 2);
    }
}
