// Autogenerated from KST: please remove this line if doing any edits by hand!

#include <boost/test/unit_test.hpp>
#include "oper_precedence_sum2.h"
#include <iostream>
#include <fstream>
#include <vector>

BOOST_AUTO_TEST_CASE(test_oper_precedence_sum2) {
    std::ifstream ifs("src/fixed_struct.bin", std::ifstream::binary);
    kaitai::kstream ks(&ifs);
    oper_precedence_sum2_t* r = new oper_precedence_sum2_t(&ks);

    BOOST_CHECK_EQUAL(r->sum(), 6);
    BOOST_CHECK_EQUAL(r->sub(), 0);
    BOOST_CHECK_EQUAL(r->mul(), 9);
    BOOST_CHECK_EQUAL(r->div_int(), 1);
    BOOST_CHECK_CLOSE(r->div_float1(), 1.0, 1e-4);
    BOOST_CHECK_CLOSE(r->div_float2(), 1.0, 1e-4);
    BOOST_CHECK_EQUAL(r->rem(), 0);
    BOOST_CHECK_EQUAL(r->shl(), 24);
    BOOST_CHECK_EQUAL(r->shr(), 0);
    BOOST_CHECK_EQUAL(r->bit_and(), 3);
    BOOST_CHECK_EQUAL(r->bit_or(), 3);
    BOOST_CHECK_EQUAL(r->bit_xor(), 0);
    BOOST_CHECK_EQUAL(r->eq(), true);
    BOOST_CHECK_EQUAL(r->ne(), false);
    BOOST_CHECK_EQUAL(r->le(), true);
    BOOST_CHECK_EQUAL(r->ge(), true);
    BOOST_CHECK_EQUAL(r->lt(), false);
    BOOST_CHECK_EQUAL(r->gt(), false);

    delete r;
}
