// Autogenerated from KST: please remove this line if doing any edits by hand!

const _imp_std = @import("std");
const _imp_kaitai_struct = @import("kaitai_struct");
const _imp_oper_precedence_sum3 = @import("../formats/oper_precedence_sum3.zig");

test "OperPrecedenceSum3" {
    const file = try _imp_std.fs.cwd().openFile("../../src/fixed_struct.bin", .{});
    defer file.close();
    var buffer: [8]u8 = undefined;
    var reader = file.reader(&buffer);
    const allocator = _imp_std.testing.allocator;
    var arena = _imp_std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    var _io = _imp_kaitai_struct.KaitaiStream.fromFileReader(&reader);
    const r = try _imp_oper_precedence_sum3.OperPrecedenceSum3.create(&arena, &_io, null, null);

    try _imp_std.testing.expectEqual(6, (try r.sum()));
    try _imp_std.testing.expectEqual(0, (try r.sub()));
    try _imp_std.testing.expectEqual(7, (try r.mul()));
    try _imp_std.testing.expectEqual(2, (try r.divInt()));
    try _imp_std.testing.expectEqual(1.6666666, (try r.divFloat1()));
    try _imp_std.testing.expectEqual(1.6666666, (try r.divFloat2()));
    try _imp_std.testing.expectEqual(3, (try r.rem()));
    try _imp_std.testing.expectEqual(17, (try r.shl()));
    try _imp_std.testing.expectEqual(1, (try r.shr()));
    try _imp_std.testing.expectEqual(3, (try r.bitAnd()));
    try _imp_std.testing.expectEqual(4, (try r.bitOr()));
    try _imp_std.testing.expectEqual(2, (try r.bitXor()));
}
