<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class OperPrecedenceSum1Test extends TestCase {
    public function testOperPrecedenceSum1() {
        $r = OperPrecedenceSum1::fromFile(self::SRC_DIR_PATH . '/fixed_struct.bin');

        $this->assertSame(6, $r->sum());
        $this->assertSame(0, $r->sub());
        $this->assertSame(7, $r->mul());
        $this->assertSame(1, $r->divInt());
        $this->assertEquals($r->divFloat1(), 1.6666666, '', 1e-6);
        $this->assertEquals($r->divFloat2(), 1.6666666, '', 1e-6);
        $this->assertSame(3, $r->rem());
        $this->assertSame(24, $r->shl());
        $this->assertSame(0, $r->shr());
        $this->assertSame(3, $r->bitAnd());
        $this->assertSame(3, $r->bitOr());
        $this->assertSame(0, $r->bitXor());
        $this->assertSame(true, $r->eq());
        $this->assertSame(false, $r->ne());
        $this->assertSame(true, $r->le());
        $this->assertSame(true, $r->ge());
        $this->assertSame(false, $r->lt());
        $this->assertSame(false, $r->gt());
    }
}
