<?php
// Autogenerated from KST: please remove this line if doing any edits by hand!

namespace Kaitai\Struct\Tests;

class OperPrecedenceSum3Test extends TestCase {
    public function testOperPrecedenceSum3() {
        $r = OperPrecedenceSum3::fromFile(self::SRC_DIR_PATH . '/fixed_struct.bin');

        $this->assertSame(6, $r->sum());
        $this->assertSame(0, $r->sub());
        $this->assertSame(7, $r->mul());
        $this->assertSame(2, $r->divInt());
        $this->assertEquals($r->divFloat1(), 1.6666666, '', 1e-6);
        $this->assertEquals($r->divFloat2(), 1.6666666, '', 1e-6);
        $this->assertSame(3, $r->rem());
        $this->assertSame(17, $r->shl());
        $this->assertSame(1, $r->shr());
        $this->assertSame(3, $r->bitAnd());
        $this->assertSame(4, $r->bitOr());
        $this->assertSame(2, $r->bitXor());
    }
}
