// Autogenerated from KST: please remove this line if doing any edits by hand!

#include <boost/test/unit_test.hpp>
#include "oper_precedence_sum3.h"
#include <iostream>
#include <fstream>
#include <vector>

BOOST_AUTO_TEST_CASE(test_oper_precedence_sum3) {
    std::ifstream ifs("src/fixed_struct.bin", std::ifstream::binary);
    kaitai::kstream ks(&ifs);
    oper_precedence_sum3_t* r = new oper_precedence_sum3_t(&ks);

    BOOST_CHECK_EQUAL(r->sum(), 6);
    BOOST_CHECK_EQUAL(r->sub(), 0);
    BOOST_CHECK_EQUAL(r->mul(), 7);
    BOOST_CHECK_EQUAL(r->div_int(), 2);
    BOOST_CHECK_CLOSE(r->div_float1(), 1.6666666, 1e-4);
    BOOST_CHECK_CLOSE(r->div_float2(), 1.6666666, 1e-4);
    BOOST_CHECK_EQUAL(r->rem(), 3);
    BOOST_CHECK_EQUAL(r->shl(), 17);
    BOOST_CHECK_EQUAL(r->shr(), 1);
    BOOST_CHECK_EQUAL(r->bit_and(), 3);
    BOOST_CHECK_EQUAL(r->bit_or(), 4);
    BOOST_CHECK_EQUAL(r->bit_xor(), 2);

    delete r;
}
