# Autogenerated from KST: please remove this line if doing any edits by hand!

import unittest

from oper_precedence_sum3 import _schema

class TestOperPrecedenceSum3(unittest.TestCase):
    def test_oper_precedence_sum3(self):
        r = _schema.parse_file('src/fixed_struct.bin')

        self.assertEqual(r.sum, 6)
        self.assertEqual(r.sub, 0)
        self.assertEqual(r.mul, 7)
        self.assertEqual(r.div_int, 2)
        self.assertAlmostEqual(r.div_float1, 1.6666666, 6)
        self.assertAlmostEqual(r.div_float2, 1.6666666, 6)
        self.assertEqual(r.rem, 3)
        self.assertEqual(r.shl, 17)
        self.assertEqual(r.shr, 1)
        self.assertEqual(r.bit_and, 3)
        self.assertEqual(r.bit_or, 4)
        self.assertEqual(r.bit_xor, 2)
