// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecOperPrecedenceSum3 : CommonSpec
    {
        [Test]
        public void TestOperPrecedenceSum3()
        {
            var r = OperPrecedenceSum3.FromFile(SourceFile("fixed_struct.bin"));

            Assert.AreEqual(r.Sum, 6);
            Assert.AreEqual(r.Sub, 0);
            Assert.AreEqual(r.Mul, 7);
            Assert.AreEqual(r.DivInt, 2);
            Assert.AreEqual(r.DivFloat1, 1.6666666, 1e-6);
            Assert.AreEqual(r.DivFloat2, 1.6666666, 1e-6);
            Assert.AreEqual(r.Rem, 3);
            Assert.AreEqual(r.Shl, 17);
            Assert.AreEqual(r.Shr, 1);
            Assert.AreEqual(r.BitAnd, 3);
            Assert.AreEqual(r.BitOr, 4);
            Assert.AreEqual(r.BitXor, 2);
        }
    }
}
