// Autogenerated from KST: please remove this line if doing any edits by hand!

using NUnit.Framework;

namespace Kaitai
{
    [TestFixture]
    public class SpecOperPrecedenceSum1 : CommonSpec
    {
        [Test]
        public void TestOperPrecedenceSum1()
        {
            var r = OperPrecedenceSum1.FromFile(SourceFile("fixed_struct.bin"));

            Assert.AreEqual(r.Sum, 6);
            Assert.AreEqual(r.Sub, 0);
            Assert.AreEqual(r.Mul, 7);
            Assert.AreEqual(r.DivInt, 1);
            Assert.AreEqual(r.DivFloat1, 1.6666666, 1e-6);
            Assert.AreEqual(r.DivFloat2, 1.6666666, 1e-6);
            Assert.AreEqual(r.Rem, 3);
            Assert.AreEqual(r.Shl, 24);
            Assert.AreEqual(r.Shr, 0);
            Assert.AreEqual(r.BitAnd, 3);
            Assert.AreEqual(r.BitOr, 3);
            Assert.AreEqual(r.BitXor, 0);
            Assert.AreEqual(r.Eq, true);
            Assert.AreEqual(r.Ne, false);
            Assert.AreEqual(r.Le, true);
            Assert.AreEqual(r.Ge, true);
            Assert.AreEqual(r.Lt, false);
            Assert.AreEqual(r.Gt, false);
        }
    }
}
