-- Autogenerated from KST: please remove this line if doing any edits by hand!

local luaunit = require("luaunit")

require("oper_precedence_sum2")

TestOperPrecedenceSum2 = {}

function TestOperPrecedenceSum2:test_oper_precedence_sum2()
    local r = OperPrecedenceSum2:from_file("src/fixed_struct.bin")

    luaunit.assertEquals(r.sum, 6)
    luaunit.assertEquals(r.sub, 0)
    luaunit.assertEquals(r.mul, 9)
    luaunit.assertEquals(r.div_int, 1)
    luaunit.assertAlmostEquals(r.div_float1, 1.0, 0.000001)
    luaunit.assertAlmostEquals(r.div_float2, 1.0, 0.000001)
    luaunit.assertEquals(r.rem, 0)
    luaunit.assertEquals(r.shl, 24)
    luaunit.assertEquals(r.shr, 0)
    luaunit.assertEquals(r.bit_and, 3)
    luaunit.assertEquals(r.bit_or, 3)
    luaunit.assertEquals(r.bit_xor, 0)
    luaunit.assertEquals(r.eq, true)
    luaunit.assertEquals(r.ne, false)
    luaunit.assertEquals(r.le, true)
    luaunit.assertEquals(r.ge, true)
    luaunit.assertEquals(r.lt, false)
    luaunit.assertEquals(r.gt, false)
end
