-- Autogenerated from KST: please remove this line if doing any edits by hand!

local luaunit = require("luaunit")

require("oper_precedence_sum3")

TestOperPrecedenceSum3 = {}

function TestOperPrecedenceSum3:test_oper_precedence_sum3()
    local r = OperPrecedenceSum3:from_file("src/fixed_struct.bin")

    luaunit.assertEquals(r.sum, 6)
    luaunit.assertEquals(r.sub, 0)
    luaunit.assertEquals(r.mul, 7)
    luaunit.assertEquals(r.div_int, 2)
    luaunit.assertAlmostEquals(r.div_float1, 1.6666666, 0.000001)
    luaunit.assertAlmostEquals(r.div_float2, 1.6666666, 0.000001)
    luaunit.assertEquals(r.rem, 3)
    luaunit.assertEquals(r.shl, 17)
    luaunit.assertEquals(r.shr, 1)
    luaunit.assertEquals(r.bit_and, 3)
    luaunit.assertEquals(r.bit_or, 4)
    luaunit.assertEquals(r.bit_xor, 2)
end
