# Autogenerated from KST: please remove this line if doing any edits by hand!

package spec::perl::TestOperPrecedenceSum3;

use strict;
use warnings;
use base qw(Test::Class);
use Test::More;
use OperPrecedenceSum3;

sub test_oper_precedence_sum3: Test(12) {
    my $r = OperPrecedenceSum3->from_file('src/fixed_struct.bin');

    is($r->sum(), 6, 'Equals');
    is($r->sub(), 0, 'Equals');
    is($r->mul(), 7, 'Equals');
    is($r->div_int(), 2, 'Equals');
    ok(abs($r->div_float1() - 1.6666666) < 1e-6, 'Approx equals');
    ok(abs($r->div_float2() - 1.6666666) < 1e-6, 'Approx equals');
    is($r->rem(), 3, 'Equals');
    is($r->shl(), 17, 'Equals');
    is($r->shr(), 1, 'Equals');
    is($r->bit_and(), 3, 'Equals');
    is($r->bit_or(), 4, 'Equals');
    is($r->bit_xor(), 2, 'Equals');
}

Test::Class->runtests;
