# Autogenerated from KST: please remove this line if doing any edits by hand!

package spec::perl::TestOperPrecedenceSum2;

use strict;
use warnings;
use base qw(Test::Class);
use Test::More;
use OperPrecedenceSum2;

sub test_oper_precedence_sum2: Test(18) {
    my $r = OperPrecedenceSum2->from_file('src/fixed_struct.bin');

    is($r->sum(), 6, 'Equals');
    is($r->sub(), 0, 'Equals');
    is($r->mul(), 9, 'Equals');
    is($r->div_int(), 1, 'Equals');
    ok(abs($r->div_float1() - 1.0) < 1e-6, 'Approx equals');
    ok(abs($r->div_float2() - 1.0) < 1e-6, 'Approx equals');
    is($r->rem(), 0, 'Equals');
    is($r->shl(), 24, 'Equals');
    is($r->shr(), 0, 'Equals');
    is($r->bit_and(), 3, 'Equals');
    is($r->bit_or(), 3, 'Equals');
    is($r->bit_xor(), 0, 'Equals');
    cmp_ok($r->eq(), '==', 1, 'Equals');
    cmp_ok($r->ne(), '==', 0, 'Equals');
    cmp_ok($r->le(), '==', 1, 'Equals');
    cmp_ok($r->ge(), '==', 1, 'Equals');
    cmp_ok($r->lt(), '==', 0, 'Equals');
    cmp_ok($r->gt(), '==', 0, 'Equals');
}

Test::Class->runtests;
