# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../compiled/nim/oper_precedence_sum3
import auxiliary/test_utils

let r = OperPrecedenceSum3.fromFile("../../src/fixed_struct.bin")

assert r.sum == 6
assert r.sub == 0
assert r.mul == 7
assert r.divInt == 2
assert r.divFloat1 == 1.6666666
assert r.divFloat2 == 1.6666666
assert r.rem == 3
assert r.shl == 17
assert r.shr == 1
assert r.bitAnd == 3
assert r.bitOr == 4
assert r.bitXor == 2
