# Autogenerated from KST: please remove this line if doing any edits by hand!

import os, streams, options, sequtils
import ../../compiled/nim/oper_precedence_sum1
import auxiliary/test_utils

let r = OperPrecedenceSum1.fromFile("../../src/fixed_struct.bin")

assert r.sum == 6
assert r.sub == 0
assert r.mul == 7
assert r.divInt == 1
assert r.divFloat1 == 1.6666666
assert r.divFloat2 == 1.6666666
assert r.rem == 3
assert r.shl == 24
assert r.shr == 0
assert r.bitAnd == 3
assert r.bitOr == 3
assert r.bitXor == 0
assert r.eq == true
assert r.ne == false
assert r.le == true
assert r.ge == true
assert r.lt == false
assert r.gt == false
