// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"runtime/debug"
	"os"
	"testing"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	. "test_formats"
	"github.com/stretchr/testify/assert"
)

func TestOperPrecedenceSum2(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			debug.PrintStack()
			t.Fatal("unexpected panic:", r)
		}
	}()
	f, err := os.Open("../../src/fixed_struct.bin")
	if err != nil {
		t.Fatal(err)
	}
	s := kaitai.NewStream(f)
	var r OperPrecedenceSum2
	err = r.Read(s, &r, &r)
	if err != nil {
		t.Fatal(err)
	}

	tmp1, err := r.Sum()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 6, tmp1)
	tmp2, err := r.Sub()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 0, tmp2)
	tmp3, err := r.Mul()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 9, tmp3)
	tmp4, err := r.DivInt()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 1, tmp4)
	tmp5, err := r.DivFloat1()
	if err != nil {
		t.Fatal(err)
	}
	assert.InDelta(t, 1.0, tmp5, 1e-6)
	tmp6, err := r.DivFloat2()
	if err != nil {
		t.Fatal(err)
	}
	assert.InDelta(t, 1.0, tmp6, 1e-6)
	tmp7, err := r.Rem()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 0, tmp7)
	tmp8, err := r.Shl()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 24, tmp8)
	tmp9, err := r.Shr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 0, tmp9)
	tmp10, err := r.BitAnd()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 3, tmp10)
	tmp11, err := r.BitOr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 3, tmp11)
	tmp12, err := r.BitXor()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 0, tmp12)
	tmp13, err := r.Eq()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, true, tmp13)
	tmp14, err := r.Ne()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, false, tmp14)
	tmp15, err := r.Le()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, true, tmp15)
	tmp16, err := r.Ge()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, true, tmp16)
	tmp17, err := r.Lt()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, false, tmp17)
	tmp18, err := r.Gt()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, false, tmp18)
}
