// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"runtime/debug"
	"os"
	"testing"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	. "test_formats"
	"github.com/stretchr/testify/assert"
)

func TestOperPrecedenceSum3(t *testing.T) {
	defer func() {
		if r := recover(); r != nil {
			debug.PrintStack()
			t.Fatal("unexpected panic:", r)
		}
	}()
	f, err := os.Open("../../src/fixed_struct.bin")
	if err != nil {
		t.Fatal(err)
	}
	s := kaitai.NewStream(f)
	var r OperPrecedenceSum3
	err = r.Read(s, &r, &r)
	if err != nil {
		t.Fatal(err)
	}

	tmp1, err := r.Sum()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 6, tmp1)
	tmp2, err := r.Sub()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 0, tmp2)
	tmp3, err := r.Mul()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 7, tmp3)
	tmp4, err := r.DivInt()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 2, tmp4)
	tmp5, err := r.DivFloat1()
	if err != nil {
		t.Fatal(err)
	}
	assert.InDelta(t, 1.6666666, tmp5, 1e-6)
	tmp6, err := r.DivFloat2()
	if err != nil {
		t.Fatal(err)
	}
	assert.InDelta(t, 1.6666666, tmp6, 1e-6)
	tmp7, err := r.Rem()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 3, tmp7)
	tmp8, err := r.Shl()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 17, tmp8)
	tmp9, err := r.Shr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 1, tmp9)
	tmp10, err := r.BitAnd()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 3, tmp10)
	tmp11, err := r.BitOr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 4, tmp11)
	tmp12, err := r.BitXor()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 2, tmp12)
}
